In [1]:
import pandas as pd #Import Pandas

In [3]:
info={
    "name" : ["siraj","affan","massy"],
    "CGPA" : [7.8,6.9,9.0]
}
df= pd.DataFrame(info)
print(df)

     name  CGPA
0   siraj   7.8
1   affan   6.9
2  masira   9.0

In [9]:
s=pd.Series([1,2,3,4,5,6])
print(s)
print(type(s))

#indexing
print(s[0])
print(s[1])
print(s[2])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>
1
2
3

In [16]:
s1=pd.Series([1,2,3,4,5,6],index=["a","b","c","d","e","f"])
print(s1)
print(s1["a"])#By label
print(s1[0])#By index
print(s1.index)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64
1
1
Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

C:\Users\siraj\AppData\Local\Temp\ipykernel_12436\53141807.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s1[0])#By index

In [20]:
s1=pd.Series([1,2,4,5,6])
s2=pd.Series([10,20,40,50,60])
print(s1+s2) #vectorized opration
change_s1=s1.drop(0)

print(change_s1)
print(s1)

0    11
1    22
2    44
3    55
4    66
dtype: int64
1    2
2    4
3    5
4    6
dtype: int64
0    1
1    2
2    4
3    5
4    6
dtype: int64

In [23]:
df1={
    "name":["siraj","massy"],
     "ID":[1,2]
}
df=pd.DataFrame(df1)
print(df)

    name  ID
0  siraj   1
1  massy   2

In [25]:
df2=pd.DataFrame([["siraj",1],["affan",2],["massy",3]],columns=["name","age"])
print(df2)

    name  age
0  siraj    1
1  affan    2
2  massy    3

In [27]:
#using numpy array 
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
df=pd.DataFrame(arr,columns=["a","b","c","])
print(df)

   a  b  c  d
0  1  2  3  4
1  5  6  7  8

In [29]:
#csv Data
emp1=pd.read_csv("Emp.csv")
print(emp1,type(emp1))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [30]:
#json Data
emp2=pd.read_json("Sample.json")
print(emp2,type(emp2))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [31]:
emp1

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [51]:
#methods
# emp1.head(#Pass Value exmple 1-2-3-)
# emp1.tail(#Pass Value exmple 1-2-3-)
# emp1.sample(#Pass Value exmple 1-2-3-)
# emp1.info()
# emp1.shape
# emp1.describe()
# emp1.nunique()
# emp1.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [8]:
# AQI DATA SET REAL EXAMPLE
aqi=pd.read_csv("globalAirQuality.csv")
df=pd.DataFrame(aqi)
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [56]:
df[""]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [78]:
df[["city","aqi"]]
df.iloc[0]
df.iloc[0:2]#st index , end index(inclusive)
df.iloc[0]
df.iloc[0:2]#st index , end index(exclusive)

#cells ( rows and column)
df.loc[0:2,["city","aqi"]]
df.columns
df.iloc[0:2,[2,11]]
city1=df["city"].copy()
print(city1)
city1[0]="Solapur"
city1

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

0         Solapur
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [41]:
#filtring our data
df[df["aqi"]>100]
df[(df["aqi"]>100)&(df["humidity"]>70)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
13,2025-11-05 07:25:17.554219,US,New York,40.713,-74.006,26.147,58.714,49.826,5.228,51.651,0.615,124,27.299,76.014,0.786
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
16,2025-11-05 10:25:17.554219,US,New York,40.713,-74.006,2.799,69.074,52.218,5.538,37.461,0.600,130,7.884,74.873,3.401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [20]:
df.query("aqi>100 & so2 > 15.539")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
425,2025-11-07 11:25:17.554219,US,Los Angeles,34.052,-118.244,46.807,97.397,40.553,16.559,50.303,0.317,101,19.615,34.083,2.234

In [7]:
df1=pd.read_csv("raw_data.csv")
# df1.isnull()
# df1.isna()
# df1.dropna(axis=1)
# df1.fillna(0)


# df1.ffill()  #forward fill
df1.bfill()  #Backword fill
# df1["age"].duplicated()
df1.drop_duplicates(inplace=True)#changes in original data

In [6]:
#data typesdf1.dtypes
df1["gender"].str.lower()
df1["gender"].str.strip()

NameError: name 'df1' is not defined

In [68]:
df1

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [10]:
#feature engineering 
df2=df1.copy()
df2["tax"]=df2["income"].apply(lambda x: "20%" if x >=500 else "10%")
df2
df2_dic={"Male" : "m" , "Female": "f", "NaN":"O"}
df2["gender"]=df2["gender"].map(df2_dic)
df2

df3=df2.assign(new_income =df2["income"] * 1.1)
df3

df2["country"]=df2["country"].replace("USA" ,"INDIA")
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0   INDIA      m  55000.0  20%
2    2    Jane Smith   NaN  Canada      f  62000.0  20%
3    3          Alex   NaN   INDIA    NaN  47000.0  20%
4    4  Maria Garcia  34.0   Spain      f      NaN  10%
5    5        Li Wei  27.0   China      m  51000.0  20%
6    6           NaN  45.0   India      f  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      m  68000.0  20%
8    8    Rachel Lee  29.0   INDIA      f  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      m  45000.0  20%
10  10   Emily Davis  31.0   INDIA    NaN  58000.0  20%

In [12]:
clean_data=df1.copy()
df1_mean=clean_data["age"].mean()
clean_data["age"]=clean_data["age"].fillna(df1_mean)
clean_data['age'] = clean_data['age'].astype(int)

clean_data

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith   33  Canada   Female  62000.0
3    3          Alex   33     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      NaN
5    5        Li Wei   27   China     Male  51000.0
6    6           NaN   45   India   Female  73000.0
7    7    Ahmed Khan   38     NaN     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz   33  Mexico     Male  45000.0
10  10   Emily Davis   31     USA      NaN  58000.0

In [11]:
df2=df2.rename(columns={"income":"Salary"})
df2=df2.rename(index={"1":"First"})
df2=df2.sort_values("Salary")
df2=df2.reset_index(drop=True)
df2

   id          name   age country gender   Salary  tax
0   9   Carlos Ruiz   NaN  Mexico      m  45000.0  20%
1   3          Alex   NaN   INDIA    NaN  47000.0  20%
2   5        Li Wei  27.0   China      m  51000.0  20%
3   1      John Doe  29.0   INDIA      m  55000.0  20%
4  10   Emily Davis  31.0   INDIA    NaN  58000.0  20%
5   2    Jane Smith   NaN  Canada      f  62000.0  20%
6   8    Rachel Lee  29.0   INDIA      f  62000.0  20%
7   7    Ahmed Khan  38.0     NaN      m  68000.0  20%
8   6           NaN  45.0   India      f  73000.0  20%
9   4  Maria Garcia  34.0   Spain      f      NaN  10%

In [16]:
df5=df2.copy()
new_col_order=[col for col in df5.columns if col != "id"]+["id"]
# print(new_col_order)
df2=df2[new_col_order]
df2

           name   age country gender   Salary  tax  id
0   Carlos Ruiz   NaN  Mexico      m  45000.0  20%   9
1          Alex   NaN   INDIA    NaN  47000.0  20%   3
2        Li Wei  27.0   China      m  51000.0  20%   5
3      John Doe  29.0   INDIA      m  55000.0  20%   1
4   Emily Davis  31.0   INDIA    NaN  58000.0  20%  10
5    Jane Smith   NaN  Canada      f  62000.0  20%   2
6    Rachel Lee  29.0   INDIA      f  62000.0  20%   8
7    Ahmed Khan  38.0     NaN      m  68000.0  20%   7
8           NaN  45.0   India      f  73000.0  20%   6
9  Maria Garcia  34.0   Spain      f      NaN  10%   4

In [30]:
final=df1.copy()
final=final.drop_duplicates()
final=final.fillna(0)
final=final.sort_values("income")
final=final.reset_index(drop=True)
final.to_csv("Sorted_Data.csv")

In [29]:
final

   id          name   age country   gender   income
0   4  Maria Garcia  34.0   Spain   Female      0.0
1   9   Carlos Ruiz   0.0  Mexico     Male  45000.0
2   3          Alex   0.0     USA  Unknown  47000.0
3   5        Li Wei  27.0   China     Male  51000.0
4   1      John Doe  29.0     USA     Male  55000.0
5  10   Emily Davis  31.0     USA        0  58000.0
6   2    Jane Smith   0.0  Canada   Female  62000.0
7   8    Rachel Lee  29.0     USA   Female  62000.0
8   7    Ahmed Khan  38.0       0     Male  68000.0
9   6             0  45.0   India   Female  73000.0

In [48]:
df2
# df2.groupby("country")["income"].mean()
# df2.groupby("country")["income"].max()
# df2.groupby("country")["income"].min()
df2.groupby("country").agg({
    "income":"mean",
    "age":"max"
})

KeyError: "Label(s) ['income'] do not exist"

In [46]:
df2

           name   age country gender   Salary  tax  id
0   Carlos Ruiz   NaN  Mexico      m  45000.0  20%   9
1          Alex   NaN   INDIA    NaN  47000.0  20%   3
2        Li Wei  27.0   China      m  51000.0  20%   5
3      John Doe  29.0   INDIA      m  55000.0  20%   1
4   Emily Davis  31.0   INDIA    NaN  58000.0  20%  10
5    Jane Smith   NaN  Canada      f  62000.0  20%   2
6    Rachel Lee  29.0   INDIA      f  62000.0  20%   8
7    Ahmed Khan  38.0     NaN      m  68000.0  20%   7
8           NaN  45.0   India      f  73000.0  20%   6
9  Maria Garcia  34.0   Spain      f      NaN  10%   4

In [64]:
#melt & Pivot

df=pd.DataFrame({
    "country" : ["usa","usa","india","india"],
    "year" : [2020,2021,2020,2021],
    "sales": [100,120,90,110],
    "profit":[20,25,18,22],
    "tax":[20,20,10,20]
})
melted_df= df.melt(
    id_vars=["country","year"],
    value_vars=["sales","profit","tax"],
    var_name="metrics",
    value_name="value"
)
original=melted_df.pivot(
    index=["country","year"],
    columns="matrics",
    values="values"
)
original

KeyError: 'matrics'

In [59]:
df

  country  year  sales  profit  tax
0     usa  2020    100      20   20
1     usa  2021    120      25   20
2   india  2020     90      18   10
3   india  2021    110      22   20